Updated puppetBuildStandalone for ubuntu

diff --git a/modules/base/files/local.bin/puppetBuildStandalone b/modules/base/files/local.bin/puppetBuildStandalone
--- a/modules/base/files/local.bin/puppetBuildStandalone
+++ b/modules/base/files/local.bin/puppetBuildStandalone
@@ -79,15 +79,15 @@ distro=$(lsb_release -i | awk '{print $3}')
 module_dir=/etc/puppetlabs/code/environments/${environment}/modules
 
 case ${distro} in
-    CentOS|RedHatEnterpriseServer)      puppet=/opt/puppetlabs/bin/puppet
-                                        module_dir=/etc/puppetlabs/puppet/code/environments/${environment}/modules
-                                        ;;
-    AmazonAMI|Ubuntu)                   puppet=/usr/bin/puppet
-                                        module_dir=/etc/puppet/environments/${environment}/modules
-                                        ;;
-    "*")                                echo "Error: Distribution ${distro} not supported"
-                                        exit 1
-                                        ;;
+    CentOS|RedHatEnterpriseServer|Ubuntu)   puppet=/opt/puppetlabs/bin/puppet
+                                            module_dir=/etc/puppetlabs/puppet/code/environments/${environment}/modules
+                                            ;;
+    AmazonAMI)                              puppet=/usr/bin/puppet
+                                            module_dir=/etc/puppet/environments/${environment}/modules
+                                            ;;
+    "*")                                    echo "Error: Distribution ${distro} not supported"
+                                            exit 1
+                                            ;;
 esac
 
 echo -e "\nInfo: Building a $ROLE server from the ${environment} repository\n"
